GoatBook/accounts/urls.py
from django.conf.urls import url
from accounts import views
from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^send_login_email', views.send_login_email, name='send_login_email'),
    url(r'^login', views.login, name='login'),
    url(r'^logout$', logout, {'next_page': '/'}, name='logout'),
]

GoatBook/book_2/urls.py
from django.conf.urls import include, url
from lists import views as list_views  
from lists import urls as list_urls
from accounts import urls as accounts_urls  

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
    url(r'^accounts/', include(accounts_urls)),
    # url(r'^admin/', include(admin.site.urls)),
]

GoatBook/lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
]

GoatBook/accounts/models.py
from django.db import models
import uuid
from django.contrib import auth

auth.signals.user_logged_in.disconnect(auth.models.update_last_login)

class User(models.Model):
    email = models.EmailField(primary_key=True)
    REQUIRED_FIELDS = ()
    USERNAME_FIELD = 'email'
    
    def is_authenticated(self):
        return True
    
class Token(models.Model):
    email = models.EmailField(primary_key=True)
    uid = models.CharField(default=uuid.uuid4, max_length=40)

GoatBook/lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class List(models.Model):
    
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

class Item(models.Model):
    text = models.TextField(default = '')
    list = models.ForeignKey(List, default=None)
    
    def __str__(self):
        return self.text
    
    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

GoatBook/lists/forms.py
'''
Created on Oct 26, 2016

@author: lpa
'''
from django import forms
from lists.models import Item
from django.core.exceptions import ValidationError

EMPTY_ITEM_ERROR = "no empty items"
DUPLICATE_ITEM_ERROR = "item already exists"

class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'enter item',
                'class': 'form-control input-lg',
            })}
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }
        
    def save(self, for_list):
        self.instance.list = for_list
        return super().save()

class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)
    
    def save(self):
        return forms.models.ModelForm.save(self)

GoatBook/accounts/views.py
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.contrib import auth, messages
from accounts.models import Token
from django.core.urlresolvers import reverse

def send_login_email(request):
    email = request.POST['email']
    token = Token.objects.create(email=email)
    url = request.build_absolute_uri(
        reverse('login') + '?token={uid}'.format(uid=str(token.uid))
    )
    message_body = 'login link: {url}'.format(url=url)
    send_mail(
        'login link',
        message_body,
        'noreply@superlists',
        [email],
    )
    
    messages.success(request,"sent")
    return redirect('/')

def login(request):
    user = auth.authenticate(uid=request.GET.get('token'))
    if user:
        auth.login(request, user)
    return redirect('/')

GoatBook/lists/views.py
from django.shortcuts import render, redirect
from lists.models import Item, List
from lists.forms import ItemForm, ExistingListItemForm


# Create your views here.
def home_page(request):
    return render(request, 'home.html', {'form':ItemForm()})

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, "form": form})

def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {'form' : form})

GoatBook/lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>todo lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
</head>
	<body>
<div class="container">
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">mybar</a>
    {% if user.email %}
      <ul class="nav navbar-nav navbar-right">
        <li class="navbar-text">logged as {{ user.email }}</li>
        <li><a href="{% url 'logout' %}">logout</a></li>
      </ul>
    {% else %}
      <form class="navbar-form navbar-right" method="POST" action="{% url 'send_login_email' %}">
        <span>enter email:</span>
        <input class="form-control" name="email" type="text" />
        {% csrf_token %}
      </form>
    {% endif %}
  </div>
</nav>

{% if messages %}
        <div class="row">
          <div class="col-md-8">
            <ul class="messages">
              {% for message in messages %}
                {% if message.tags == 'success' %}
                  <li class="alert alert-success">
                {% else %}
                  <li class="alert alert-warning">
                {% endif %}"
                  {{ message }}
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      {% endif %}
  
    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">
                <h1>{% block header_text %}{% endblock %}</h1>
                 <form method="POST" action="{% block form_action %}{% endblock %}">
        			{{ form.text }}
        			{% csrf_token %}
       				{% if form.errors %}  
            			<div class="form-group has-error">
                			<div class="help-block">{{ form.text.errors }}</div>  
            			</div>
        			{% endif %}
    			</form>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}
        </div>
    </div>

</div>

<script src="/static/jquery-3.1.1.min.js"></script>
<script src="/static/list.js"></script>

<script>
$(document).ready(function () {
  window.Superlists.initialize();
});
</script>

</body>
</html>

GoatBook/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}todo lists{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

GoatBook/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}your todo list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}